apt_http_packages:
  - nginx
yum_http_packages:
  - nginx
  - libsemanage-python
  - libselinux-python
 
default_home: "{{ '/var/www/html' if (ansible_os_family == 'Debian') else '/usr/share/nginx/html' }}"

site_deb: "local-deb.site"
site_cent: "local-cent.site"

virtual_hosts:  
  - { name: "{{ site_cent }}", ip: "{{ hostvars[\"host13\"].ansible_host }}"}
  - { name: "{{ site_deb }}", ip: "{{ hostvars[\"host14\"].ansible_host }}"}
