---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: jenkins
  validation: client
