jump_sa:
  hosts:
    bastion:
      ansible_host: 178.124.206.53 
      ansible_user: jump_sa

all_workers:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q jump_sa@178.124.206.53"'
  children:
    work_sa:
      hosts:
        host13:
          ansible_host: 192.168.202.13
        host14:
          ansible_host: 192.168.202.14
#    kubernetus:
 #     hosts:
  #      k8s13:
   #       ansible_host: 192.168.203.13
    #    k8s14:
     #     ansible_host: 192.168.203.14
    ansible:
      hosts:
        ansible7:
          ansible_host: 192.168.201.7
#ungrouped:
#  hosts:
 #   local:
  #    ansible_user: 127.0.0.1
